FreeFeed/freefeed-react-client

- package.json
- src/components/layout.jsx
- src/components/login.jsx
- src/components/sidebar.jsx
- src/components/signin.jsx
- src/config.js
- src/index.jsx
- src/redux/action-creators.js
- src/redux/configure-store.js
- src/redux/middlewares.js
- src/redux/reducers.js
- src/services/api.js
- src/services/auth.js
- src/utils/index.js
Request closes #6 with login/logout functionality
> Basic login functionality

- src/components/home.jsx
- src/components/more-comments-wrapper.jsx
- src/components/post-comments.jsx
- src/components/post-likes.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
> Implement likes

- src/components/feed-post.jsx
- src/components/home.jsx
- src/components/layout.jsx
- src/components/more-comments-wrapper.jsx
- src/components/post-comment.jsx
- src/components/post-likes.jsx
- src/components/sidebar.jsx
- src/components/user-name.jsx
- src/config.js
- src/redux/reducers.js
- src/utils/index.js
- styles/helvetica/app.scss
- styles/shared/user-name.scss
> UserName component

- src/components/layout.jsx
- src/components/sidebar.jsx
- src/config.js
- src/index.jsx
- src/redux/action-creators.js
- src/redux/configure-store.js
- src/redux/middlewares.js
- src/redux/reducers.js
- src/services/auth.js
- src/utils/index.js
Closes #20
Cleaned up login/logout workflow and got rid of nasty bug with default route and home-feed request along a way
> Persisting user-info in localStorage

- src/components/feed-post.jsx
- src/components/home.jsx
- src/components/post-comments.jsx
- src/components/post-likes.jsx
- src/redux/action-creators.js
- src/redux/configure-store.js
- src/redux/middlewares.js
- src/redux/reducers.js
- src/services/api.js
- styles/helvetica/post.scss
> Implement post editing

- src/components/feed-post.jsx
- src/components/home.jsx
- src/redux/action-creators.js
- src/redux/middlewares.js
- src/redux/reducers.js
- src/services/api.js
> Add ability to delete the post

- src/components/feed-post.jsx
- src/components/home.jsx
- src/components/post-comment.jsx
- src/components/post-comments.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
- styles/shared/comments.scss
> Edit comment

- src/components/feed-post.jsx
- src/components/home.jsx
- src/components/post-comment.jsx
- src/components/post-comments.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
> Add comment

- src/components/feed-post.jsx
- src/components/home.jsx
> Change like label if user liked the post

- src/components/layout.jsx
> Correct link to home from anywhere

- src/components/create-post.jsx
- src/components/home.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
- styles/shared/create-post.scss
> Add ability to create post

- src/components/create-post.jsx
- src/components/loader-container.jsx
- styles/shared/loader-container.scss
> A throbbing fix!

- src/components/feed-post.jsx
- src/components/home.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
> Add like/unlike

- src/components/footer.jsx
- src/components/layout.jsx
- src/components/sidebar.jsx
> Fix the sidebar and footer.

- src/components/login.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- styles/shared/loader-container.scss
> Fixing login issues with more action-creating and further reducing

- src/components/sidebar.jsx
- styles/helvetica/sidebar.scss
> Fix avatar styles in sidebar

- src/components/post-attachment-audio.jsx
- src/components/post-attachments.jsx
- styles/helvetica/post.scss
- styles/shared/create-post.scss
> Audio attachments

- styles/shared/single-post.scss
- styles/shared/timeline-post.scss
> [attachments] Update margins for mobile screens

- package.json
- src/components/home.jsx
- src/components/post-likes.jsx
- src/redux/reducers.js
- test/index.js
- test/react-test/post-likes.js
- test/redux-test/reducers/signInForm.js
- test/redux-test/reducers/unauthenticatedClearsState.js
- webpack.config.js
> Testing flow + fixes

- package.json
- src/components/create-post.jsx
- src/components/feed-post.jsx
- src/components/post-comment.jsx
- src/redux/reducers.js
- src/services/api.js
- styles/shared/comments.scss
- styles/shared/create-post.scss
- styles/shared/forms.scss
- styles/shared/timeline-post.scss
Closes #33, closes #55 
Also fixes a bug that appears while editing expanded comments.
> Replace vanilla textarea with react resizable one

- src/components/create-post.jsx
- src/components/feed-post.jsx
- src/components/home.jsx
- src/components/layout.jsx
- src/components/loader-container.jsx
- src/components/post-comment.jsx
- src/components/sidebar.jsx
- src/components/signin.jsx
- src/components/user-name.jsx
- src/index.jsx
- src/redux/action-creators.js
- src/redux/configure-store.js
- src/redux/reducers.js
- src/services/api.js
- styles/shared/loader-container.scss
> Discussions route

- package.json
- src/components/home.jsx
- src/components/layout.jsx
- src/components/sidebar.jsx
- src/components/user-name.jsx
- src/index.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
> User feed route handler

- src/components/post-comments.jsx
- test/react-test/post-comments.js
Closes #35 while preserving behavior
> Add test suite for PostComments component

- package.json
- src/components/create-post.jsx
- src/components/feed-post.jsx
- src/components/home-feed.jsx
- src/components/home.jsx
- src/components/select-utils.js
- src/components/single-post.jsx
- src/index.jsx
- src/redux/action-creators.js
- src/redux/configure-store.js
- src/redux/middlewares.js
- src/redux/reducers.js
- styles/shared/single-post.scss
Closes #50 
Also fix several bugs
> Display single post page

- src/components/feed-post.jsx
- src/components/home.jsx
- src/components/post-comment.jsx
- src/components/post-comments.jsx
- src/components/single-post.jsx
- styles/shared/comments.scss
> Single post improvements

- src/components/feed-post.jsx
- src/components/post-comment.jsx
- src/components/post-text.jsx
- src/utils/index.js
- test/utils-test/showHtmlEnters.js
> Support multiline text for posts and comments

- package.json
- webpack.config.js
> Add babel-polyfill for ie

- src/utils/index.js
- test/utils-test/showHtmlEnters.js
> Preserve one-lined texts

- src/components/post-comment.jsx
> Clear comment field after posting comment

- src/components/home.jsx
- src/components/post-text.jsx
- src/components/select-utils.js
- src/components/single-post.jsx
- src/redux/reducers.js
> Single post state

- src/components/home.jsx
- src/components/paginated-view.jsx
- src/components/pagination-links.jsx
- src/components/sidebar.jsx
- src/index.jsx
- src/redux/configure-store.js
- src/redux/route-actions.js
> Paginated view

- package.json
- src/components/feed-post.jsx
- src/components/select-utils.js
- src/components/sidebar.jsx
- src/components/user-name.jsx
- src/index.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/redux/route-actions.js
- src/services/api.js
- styles/helvetica/post.scss
- styles/shared/single-post.scss
- styles/shared/timeline-post.scss
> Direct messages route

- package.json
- src/redux/configure-store.js
Rollback webpack-dev-server version, fix an integration with chrome redux extension
> Fix a build

- src/components/post-comments.jsx
> Add "Add comment" link

- src/components/breadcrumbs.jsx
- src/components/paginated-view.jsx
- src/components/select-utils.js
- src/components/user-feed.jsx
- src/components/user-profile.jsx
- src/index.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/redux/route-actions.js
- src/services/api.js
- src/utils/index.js
> User actions (subscriptions, blocking) and comments and likes feeds

- src/redux/action-creators.js
- src/redux/configure-store.js
- src/redux/middlewares.js
- src/redux/reducers.js
- webpack.config.js
> Pure reducers

- package.json
- src/components/create-post.jsx
- src/components/home.jsx
- src/components/send-to.jsx
- src/components/user-feed.jsx
- src/components/user-profile.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/services/api.js
- styles/helvetica/app.scss
- styles/helvetica/react-select.scss
- styles/shared/create-post.scss
- styles/shared/forms.scss
Add feed selector for new post, closes #80, closes #130
> Feed selector

- src/redux/reducers.js
This fixes the problem described in #136 for other cases, like, loading likes and comments.
> Fix display of default userpics (everywhere)

- src/components/feed-post.jsx
Before: `timeline.index`
After: `/username`
> Fix the link on post's userpic

- src/components/layout.jsx
- src/components/recent-groups.jsx
- src/components/sidebar.jsx
- src/redux/reducers.js
> Implement recent group list on the sidebar

- src/components/post-comments.jsx
According to https://github.com/FreeFeed/freefeed-html/issues/19.
> [comments-disabled] Add "- disabled for others" after "Add comment"

- styles/shared/attachments.scss
This change fixes the position for attachments on create-post when there's "More" menu opened.
> Fix position for attachments container

- src/components/layout.jsx
- src/redux/reducers.js
- styles/helvetica/header.scss
Some screenshots:
Phone:
Tablet:
Computer (didn't change):
> Mobile shortcuts

- src/components/user-profile.jsx
- src/components/user-settings-form.jsx
- src/redux/action-creators.js
- src/services/api.js
See also:
- https://github.com/FreeFeed/freefeed-server/pull/33 — support for the server.
> User descriptions (react client)

- src/components/group-settings-form.jsx
- src/components/group-settings.jsx
- src/components/user-profile.jsx
- src/index.jsx
- src/redux/action-creators.js
- src/redux/reducers.js
- src/redux/route-actions.js
- src/services/api.js
- styles/helvetica/app.scss
- styles/shared/settings.scss
See also:
- https://github.com/FreeFeed/freefeed-server/pull/35 — support for the server.
> Group settings, including descriptions (react client)

- src/components/user-profile.jsx
> Add link parsing to user/group descriptions

- src/components/user-feed.jsx
- src/components/user-profile.jsx
> Remove post form from Likes and Comments pages

- src/components/create-post.jsx
- src/components/feed.jsx
- src/components/post-attachment-audio.jsx
- src/components/post-attachment-general.jsx
- src/components/post-attachment-image.jsx
- src/components/post-attachments.jsx
- src/components/post.jsx
- src/components/single-post.jsx
- src/components/user-feed.jsx
- src/components/user-profile.jsx
- src/redux/reducers.js
- styles/shared/attachments.scss
This is quite simple implementation, far from the goodness we have in the Ember frontend (there's no diffs etc.). But it works, and it's been few weeks since I started this branch, so I decided to send it and then improve incrementally.
Updated: added a fix for #252.
> Remove attachments

- src/redux/middlewares.js
- src/redux/reducers.js
> Perfectly work with attachments and users in realtime posts and comments

- src/components/post.jsx
See https://github.com/FreeFeed/freefeed-react-client/issues/262#issuecomment-183496932 for the context.
> Remove unlock icon for "not really private" entries

- src/components/post.jsx
See also:
- https://github.com/FreeFeed/freefeed-server/pull/52
- https://github.com/FreeFeed/freefeed-html/pull/26
> Remove "Like" action for own entries

- src/config.js
- src/redux/reducers.js
- src/utils/index.js
This also fixes displaying of user/entry pages for anons.
> Move frontend preferences defaults to config.js

- src/components/layout.jsx
> Fast and dirty fix for logo click

- styles/helvetica/base.scss
Look at george.freefeed.net, suddenly it's wiiiiiide on desktop.
> Fix website width (conflicting CSS)

- src/components/create-post.jsx
- src/components/discussions.jsx
- src/components/home.jsx
- src/components/send-to.jsx
- src/components/user.jsx
> Fix default recipient in the feed selector

- src/redux/middlewares.js
- src/redux/reducers.js
- test/redux-test/reducers/realtime.js
> Nicely work around 'omitted-comments' number in posts

- src/redux/middlewares.js
- src/services/realtime.js
> Fixing subscription messages for sockets

- src/components/group-settings-form.jsx
- src/components/manage-subscribers.jsx
- src/components/requests.jsx
- src/components/user-profile.jsx
- src/redux/middlewares.js
- styles/shared/groups.scss
Added warning popup if user try to unprivate group
Added warning popup for group admins when they trying to unsubscribe
> Private groups last changes

- src/components/requests.jsx
Fix a bug with undisplayed requests to user's feed
Add zero data state to requests page
> Private groups
